Career Guidance System using Classification

In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [5]:
dataset = pd.read_csv('CSE_dataset01{{index ()}}.csv')
print(len(dataset))
print(dataset.head())

462
   Database Fundamentals  Computer Architecture  \
0                      2                     91   
1                     51                      2   
2                     18                      7   
3                     73                     15   
4                     87                      9   

   Distributed Computing Systems  Networking  Software Development  \
0                             43          58                    52   
1                             15          49                    98   
2                             66          81                    60   
3                             82           6                    52   
4                             68          88                    37   

   Programming Skills  AI ML  Software Engineering  Business Analysis  \
0                  26     85                    85                 66   
1                  20     82                    82                 71   
2                  65     77                    7

In [6]:
#Replace zeroes
zero_not_accepted = ['Database Fundamentals','Software Development', 'Programming Skills']

In [7]:
for column in zero_not_accepted:
    dataset[column] = dataset[column].replace(0,np.NaN)
    mean = int(dataset[column].mean(skipna=True))
    dataset[column] = dataset[column].replace(np.NaN,mean)

In [8]:
# split dataset
X = dataset.iloc[:, 0:11]
y = dataset.iloc[:, 12]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.2)

In [9]:
#feature scaling
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [10]:
len(y)

462

In [11]:
import math
math.sqrt(462)

21.494185260204677

In [12]:
# Define the model: Init K-NN
classifier = KNeighborsClassifier(n_neighbors=21, p=11,metric='euclidean')

In [13]:
# Fit Model
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=21, p=11)

In [14]:
# Predict the test set results
y_pred = classifier.predict(X_test)
y_pred

array([ 2,  5,  4,  4,  6,  4,  9,  6,  1,  8,  8,  4,  2,  6,  9,  1,  1,
        2,  8, 11,  3,  3,  5,  4,  4,  2,  1,  2,  7,  3,  3, 10,  8,  5,
       10,  8,  4,  8,  2,  8,  9,  1,  9,  9,  4,  6,  6,  3,  3,  6, 10,
        3,  1,  4,  9,  1,  4,  2,  6,  2,  8,  7,  8,  2,  9,  6, 11, 11,
        3,  8, 10,  6,  1,  1,  5,  1,  5,  7, 10,  8,  2,  2,  3,  8, 11,
        1,  3,  1,  8,  9,  8,  5,  6], dtype=int64)

In [15]:
# Evaluate Model
cm = confusion_matrix(y_test, y_pred)
print (cm)
print(f1_score(y_test, y_pred, average='micro'))

[[3 1 0 0 0 0 1 1 0 0 0]
 [2 6 0 0 0 0 0 1 0 0 0]
 [2 1 6 0 0 1 0 0 0 0 0]
 [1 1 0 5 0 0 0 1 0 0 0]
 [0 1 2 0 2 1 0 0 1 0 0]
 [0 0 0 1 0 7 1 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 1 0]
 [1 0 1 0 0 0 0 7 0 0 0]
 [0 1 0 2 0 0 0 0 5 1 0]
 [0 0 0 1 3 1 0 4 1 2 0]
 [3 0 0 1 0 0 1 0 1 1 4]]
0.5053763440860215


In [16]:
print(accuracy_score(y_test, y_pred))

0.5053763440860215


In [17]:
#saving model as a pickle
import pickle

In [18]:
pickle.dump(classifier,open("student_career_guidance_system_ml_model.sav", "wb"))
pickle.dump(sc_X, open("scaler.sav", "wb"))